name: Format by `perttier`

on:
  push:
    branches: [ "main", "feature/format-ci" ]

permissions:
  contents: write

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Format
        run: |
          npm ci
          npm run prettier

      - name: Commit
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit --author=. -m "format by actions" --allow-empty
          git push
